site_name: streaming-voice-api
repo_url: https://github.com/notnodnod/streaming-voice-api
site_url: https://notnodnod.github.io/streaming-voice-api
site_description: An
site_author: notnodnod
edit_uri: edit/main/docs/
repo_name: notnodnod/streaming-voice-api
copyright: Maintained by <a href="https://notnodnod.com">notnodnod</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [streaming_voice_api]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/notnodnod/streaming-voice-api
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/streaming-voice-api

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
